[versions]
scala = "2.12.17"
spark = "3.1.3"
transmogrifai = "0.8.0-SNAPSHOT"

[libraries]
gradleAvroPlugin = { module = "com.commercehub.gradle.plugin:gradle-avro-plugin", version = "0.16.0" }

[plugins]
